### ISSUE TITLE
Obtain 6 digit passkey

### ISSUE THREAD

**Issue by NespaLa** [jtwaleson/cowboy-bike-remote-ble#1]
What would  be the best way to find the 6 digit passkey for the bike?

**Comment by jtwaleson** [comment]
Assuming you've connected your phone to your bike, go to your phone's bluetooth settings, disconnect (unpair) the cowboy bike. Then open the cowboy app again and it will give you the digits you're supposed to enter.

**Comment by jtwaleson** [comment]
@NespaLa let me know if that works and we can close this issue.

**Comment by NespaLa** [comment]
In the advanced screen of the official app I see a
mac address
serialnumber
but also a 6 digit connection code, so I suppose that is the mystery number
needed!


Thank you!

**Comment by jtwaleson** [comment]
Ok, great!
