### ISSUE TITLE
Would this run on a Huzza32 ?

### ISSUE THREAD

**Issue by theguaz** [jtwaleson/cowboy-bike-remote-ble#2]
Hello, do you think this could run on a https://www.kiwi-electronics.com/nl/adafruit-huzzah32-esp32-feather-board-3351?search=esp32

Nice project!

**Comment by jtwaleson** [comment]
Yes, should work fine. Some ESP32 versions don't have Bluetooth (ESP32-S2), but any other version should work I believe.
