### ISSUE TITLE
NimBLEDevice.h

### ISSUE THREAD

**Issue by theguaz** [jtwaleson/cowboy-bike-remote-ble#3]
Hello, it's this the NimBLED library u are using ?
![image](https://github.com/jtwaleson/cowboy-bike-remote-ble/assets/362669/e585c568-7404-4b52-aad1-e60646e63d68)

Thank you for your help :)

**Comment by jtwaleson** [comment]
Yes it is. Not sure if the new version is compatible. If you get it working, a PR with some documentation would be appreciated.

**Comment by theguaz** [comment]
Worked like a charm, i'll make a case an a proper repo citing your work, very appreciated Jouke, thank you for your support :) 

Uploading DJI_0536_1_3.mp4…

**Comment by jtwaleson** [comment]
Great. Looking forward to seeing what you made!
