### ISSUE TITLE
Cowboy UART commands

### ISSUE THREAD

**Issue by zzzorgo** [jtwaleson/cowboy-bike-remote-ble#4]
Hello Jouke,

Thank you for the great repo! It was almost exactly what I required for my small project, but I am still missing one thing: the commands to control the bike's support level (aka Eco, Adaptive, Off). So my question is, how did you get the commands to switch the lights? Or, maybe, do you know the exact commands I need?

Some context: as you surely know, Cowboy bikes lack physical controls (at least mine C4), and I'd like to implement such controls based on esp32. That is why I need to gather as many known commands as possible. The commands from your example:
```
static uint8_t lightsOffCmd[] = {0x0A, 0x10, 0x00, 0x01, 0x00, 0x01, 0x02, 0x00, 0x00, 0xD4, 0xB1};
static uint8_t lightsOnCmd[] = {0x0A, 0x10, 0x00, 0x01, 0x00, 0x01, 0x02, 0x00, 0x01, 0x15, 0x71};
```

**Comment by jtwaleson** [comment]
Good question. If I recall correctly I looked at the source of some of the apps (Unleashed/Untamed/Bronco?) and based it on that. Or I was in contact with one of their developers and they shared it informally. However I just did a quick search and it seems like their source code is offline. Best to ask some of the other devs on reddit for a list of codes.
